config/routes.rb
Rails.application.routes.draw do

  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :customer do
   post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end

 scope module: :public do
  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  resources :customers, only: [:show]
  resource :mypage, only: [:edit, :update] do
      collection do
          get :confirm
          patch :unsubscribe
      end
  end
  resources :favorites, only: [:index]
  resources :maps, only: [:index]
  resources :post_contents, only: [:index, :show, :new, :create, :update, :destroy, :edit] do
       collection do 
           get :ranking
       end
     resources :comments, only: [:create, :destroy]
     resource :favorite, only: [:create, :destroy]
   end
 end

  

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/', :to => "homes#top"
    resources :post_contents, only: [:show, :destroy] do
       collection do 
           get :ranking
       end
       resources :comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show,] do
      member do
        patch :unsubscribe
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :post_contents, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @post_contents = @customer.post_contents
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
    @customer.update(is_active: false)
    redirect_to admin_path
  end
end

app/views/admin/customers/index.html.erb
<div class="container">
  <h1>会員一覧</h1>
  <table class="table tanle-hover table-inverse bg-light my-5">
   <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>

      </tr>
    </thead>
   <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td>
         <%= customer.id %>
         <%= image_tag customer.get_profile_image(100, 100), class: 'rounded-circle icon_image mr-3 mb-3' %>
    　    </td>
         <td><%= link_to admin_customer_path(customer.id) do %>
           <%= customer.name %>
           <% end %></td>
         <td><%= customer.email %></td>
          <td>
         <% if customer.is_active %>
           有効
         <% else %>
           退会
         <% end %>
      </td>
    </tr>
  <% end %>
    </tbody>
   </table>
    <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h3>プロフィール</h3>
        <% if @customer.profile_image.attached? %>
          <%= image_tag @customer.get_profile_image(200, 200), class: 'rounded-circle', size: '150x150' %>
        <% else %>
           <%= image_tag 'no_image', size: '100x100' %>
        <% end %>
    </div>
    <div class="col-6">
      <div class="row">
        <label class="col-6">名前</label>
          <div><%= @customer.name %></div>
        <label class="col-6">プロフィール</label>
          <div><%= @customer.introduction %></div>
      </div>
    </div>
    </div>
  </div>
</div>
      <div class="text-right">
        <% if current_admin %>
            <%= link_to '退会させる', unsubscribe_admin_customer_path(@customer), method: :patch, 'data-confirm' => '本当に退会させますか？',
                                                                             class: 'btn btn-danger' %>
        <% end %>
      </div>
<h3 class="mt-5">～投稿一覧～</h3>
<% @post_contents.each do |post| %>
 <div class="container" style="margin-top: 50px;">
    <div class="row">
      <div class="col-5">
          <% if post.main_images.attached? %>
            <div class="image_slide mr-5">
                <% post.main_images.each do |image| %>
                  <div class="image_size"><%= image_tag(image, size: '200x200') %></div>
                <% end %>
              </div>
            <% else %>
              <%= image_tag 'no_image', size: '100x100' %>
            <% end %>
        </div>
          <div class="col-7">
            <div class="item-group row">

           <label class="col-sm-5 col-item-label">位置情報</label>
           <div class="col-sm-7">
              <%= post.address %>
           </div>

            <label class="col-sm-5 col-form-label">場所名</label>
            <div class="col-sm-7">
              <%= link_to admin_post_content_path(post.id) do %>
                <%= post.name %>
              <% end %>
            </div>

            <label class="col-sm-5 col-form-label">内容</label>
            <div class="col-sm-7">
              <%= post.description %>
            </div>
    </div>
  </div>
<% end %>

<script>
  $(function() {
    $('.image_slide').slick({
        dots: true,
        centerMode: true,
        centerPadding: "0px",

    });
  });
</script>