config/routes.rb
Rails.application.routes.draw do

  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :customer do
   post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end

 scope module: :public do
  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  resources :customers, only: [:show]
  resource :mypage, only: [:edit, :update] do
      collection do
          get :confirm
          patch :unsubscribe
      end
  end
  resources :favorites, only: [:index]
  resources :maps, only: [:index]
  resources :post_contents, only: [:index, :show, :new, :create, :update, :destroy, :edit] do
       collection do 
           get :ranking
       end
     resources :comments, only: [:create, :destroy]
     resource :favorite, only: [:create, :destroy]
   end
 end

  

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/', :to => "homes#top"
    resources :post_contents, only: [:show, :destroy] do
       collection do 
           get :ranking
       end
       resources :comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show,] do
      member do
        patch :unsubscribe
      end
    end
  end
end

app/models/post_content.rb
class PostContent < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  has_one_attached :image
  has_many_attached :main_images
  has_many :comments, dependent: :destroy
  belongs_to :customer
  has_many :favorites, dependent: :destroy
  validates :main_images, presence: true

  def favorited?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/post_contents_controller.rb
class Admin::PostContentsController < ApplicationController
  before_action :authenticate_admin!
  def show
    @post_content = PostContent.find(params[:id])
    @comments = @post_content.comments
    @comment = @post_content.comments
  end

  def destroy
    @post_content = PostContent.find(params[:id])
    @post_content.destroy
    redirect_to admin_path
  end

  def ranking
    @prefecture = params[:prefecture]
    if @prefecture
      @post_contents = PostContent.includes(:favorites).where(prefectures: @prefecture).sort do |a, b|
        b.favorites.size <=> a.favorites.size
      end
    else
      @post_contents = PostContent.includes(:favorites).where(prefectures: '東京都').sort do |a, b|
        b.favorites.size <=> a.favorites.size
      end
      @prefecture = '東京都'
    end
  end
end

app/helpers/admin/post_contents_helper.rb
module Admin::PostContentsHelper
end

app/views/admin/post_contents/ranking.html.erb
<%= form_with url: ranking_admin_post_contents_path, method: :get, local: true do |f| %>
  <%= f.select :prefecture, %w[北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 熊本県 大分県 宮城県 鹿児島県 沖縄県],
               { include_blank: '選択ボックス', selected: @prefecture }, class: '' %>
  <%= f.submit '検索' %>
<% end %>
<% @post_contents.each do |post| %>

  <div class="container" style="margin-top: 50px;">
    <div class="row">
      <div class="col-5">
          <% if post.main_images.attached? %>
            <div class="image_slide mr-5">
                <% post.main_images.each do |image| %>
                  <div class="image_size"><%= image_tag(image, size: '300x300') %></div>
                <% end %>
            </div>
          <% else %>
            <%= image_tag 'no_image', size: '100x100' %>
          <% end %>
        </div>
          <div class="col-7">
            <div class="item-group row">

          <label class="col-sm-5 col-item-label">投稿者</label>
           <div class="col-sm-7">
             <%= link_to admin_customer_path(post.customer.id) do %>
               <%= post.customer.name %>
             <% end %>
           </div>

           <label class="col-sm-5 col-item-label">位置情報</label>
           <div class="col-sm-7">
              <%= post.address %>
           </div>

            <label class="col-sm-5 col-form-label">場所名</label>
            <div class="col-sm-7">
              <%= link_to admin_post_content_path(post.id) do %>
                <%= post.name %>
              <% end %>
            </div>

            <label class="col-sm-5 col-form-label">内容</label>
            <div class="col-sm-7">
              <%= post.description %>
            </div>
            <h5>いいね: <%= post.favorites.count %></h5>
    </div>
  </div>
<% end %>

<script>
  $(function() {
    $('.image_slide').slick({
        dots: true,
        centerMode: true,
        centerPadding: "0px",
    });
  });
</script>

app/views/admin/post_contents/show.html.erb
<main>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAcJDsa17yjZCtsrXy3jD9ogZ_ryBFm0LA&callback=initMap" async defer></script>
  <div class="ml-50 text-center">
    <%= link_to admin_customer_path(@post_content.customer.id) do %>
      <h3><%= @post_content.customer.name %>の投稿</h3>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <div class="map-position col-6">
      <div id='map'></div>
        <style>
         #map {
           height: 400px;
           width: 400px;
           margin: 40px;
           border-radius: 35px;
           border: 15px solid #000;
         }

    　　</style>
    　　<script>
    　　let = map

    　　  function initMap(){
            map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: <%= @post_content.latitude %>, lng: <%= @post_content.longitude %> },
              zoom: 15,
            });

            marker = new google.maps.Marker({
              position:  {lat: <%= @post_content.latitude %>, lng: <%= @post_content.longitude %> },
              map: map
            });
          }

    　　 </script>

　　  </div>

      <div class="col-6 p-5">

          <% if @post_content.main_images.attached? %>
            <div class="image_slide">
              <% @post_content.main_images.each do |image| %>
                <div class="image_size"><%= image_tag(image, width: 450) %></div>
              <% end %>
            </div>
          <% else %>
            <%= image_tag 'no_image', size: '100x100' %>
          <% end %>
        </div>
          <div class="col-8">
            <div class="item-group row">

              <label class="col-sm-5 col-item-label">位置情報</label>
           <div class="col-sm-7">
              <%= @post_content.address %>
           </div>

            <label class="col-sm-5 col-form-label">場所名</label>
            <div class="col-sm-7">
              <%= @post_content.name %>
            </div>

            <label class="col-sm-5 col-form-label">内容</label>
            <div class="col-sm-7">
              <%= @post_content.description %>
            </div>

             <% if current_admin %>
               <div class="col-10"></div>
               <%= link_to '削除', admin_post_content_path(@post_content), data: { confirm: '本当に削除しますか？' }, method: :delete,
                                                                         class: 'btn btn-danger btn-sm m-3' %>
             <% end %>

            </div>

          <div class="comment-wrapper border-top　mb-10">
            <p class="mt-5">コメント一覧</p>
          <div class="comment-index">
            <% @comments.each do |c| %>
              <div>
                <% unless c.customer.blank? %>
                　<%= c.created_at.strftime('%Y/%m/%d %H:%M:%S') %><br>
                  <a href="<%= customer_path(c.customer_id) %>">
                    <%= image_tag c.customer.get_profile_image(50, 50),
                                  class: 'rounded-circle icon_image mr-3 mb-3' %>
                  </a>
                  <% end %>
                <%= c.customer.name if c.customer.present? %>
                <br>
                <%= c.content %>
                <% if c %>
                  <%= link_to '削除', admin_post_content_comment_path(@post_content, c), data: { confirm: '本当に削除しますか？' },
                                                                                       method: :delete %>
                <% end %>
              </div>
              <br>
            <% end %>
          </div>

          <h5>いいね件数: <%= @post_content.favorites.count %></h5>
        </div>
      </div>
    </div>
  </div>
</main>

<script>
  $(function() {
    $('.image_slide').slick({
        dots: true,
    });
  });
</script>