config/routes.rb
Rails.application.routes.draw do

  # 顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_scope :customer do
   post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end

 scope module: :public do
  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  resources :customers, only: [:show]
  resource :mypage, only: [:edit, :update] do
      collection do
          get :confirm
          patch :unsubscribe
      end
  end
  resources :favorites, only: [:index]
  resources :maps, only: [:index]
  resources :post_contents, only: [:index, :show, :new, :create, :update, :destroy, :edit] do
       collection do 
           get :ranking
       end
     resources :comments, only: [:create, :destroy]
     resource :favorite, only: [:create, :destroy]
   end
 end

  

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/', :to => "homes#top"
    resources :post_contents, only: [:show, :destroy] do
       collection do 
           get :ranking
       end
       resources :comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show,] do
      member do
        patch :unsubscribe
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post_content, optional: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :post_contents, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post_content
end

app/models/post_content.rb
class PostContent < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  has_one_attached :image
  has_many_attached :main_images
  has_many :comments, dependent: :destroy
  belongs_to :customer
  has_many :favorites, dependent: :destroy
  validates :main_images, presence: true

  def favorited?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    @comment = Comment.find(params[:id])
    redirect_back(fallback_location: root_path) if @comment.destroy
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @post_contents = @customer.post_contents
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
    @customer.update(is_active: false)
    redirect_to admin_path
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @post_contents = PostContent.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      maps_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/custmers_helper.rb
module Admin::CustmersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_contents_helper.rb
module Admin::PostContentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t('errors.messages.not_saved',
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to 'Log in', new_session_path(resource_name) %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css">
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
  </head>

  <body>
     <header>

      <nav class="navbar navbar-expand-lg" style='border-bottom: 1px solid'>
        <div class="container">
         <a class="navbar-brand" href="/">
           <%= link_to root_path do %>
           <%= image_tag 'koko.png', size: '100x120' %>
           <% end %>
         </a>
         <div class="col-4"></div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if current_customer %>
            <li class="nav-item">
              <%= link_to maps_path, data: { 'turbolinks' => false }, class: 'btn btn-outline-dark' do %>
                <i class="fas fa-map-marked-alt"></i> MAP
              <% end %>
            </li>

            <% if current_customer.email != "guest@example.com" %>
              <li class="nav-item">
                <%= link_to customer_path(current_customer), class: 'btn btn-outline-dark' do %>
                  <i class="fas fa-home"></i> My Page
                <% end %>
              </li>
            <% end %>

            <li class="nav-item">
              <%= link_to ranking_post_contents_path, class: 'btn btn-outline-dark' do %>
                <i class="fas fa-crown"></i> Ranking
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to about_path, class: 'btn btn-outline-dark' do %>
                <i class="fas fa-info-circle"></i> About
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark' do %>
                <i class="fas fa-door-open"></i> Log Out
              <% end %>
            </li>

            <% elsif current_admin %>
             <li class="nav-item">
              <%= link_to 'マップ', admin_path, data: { 'turbolinks' => false }, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to 'ユーザー', admin_customers_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to 'ランキング', ranking_admin_post_contents_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>

            </li>
            <% else %>

            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash[:notice].present? %>
      <p class="notice mb-0"><%= flash[:notice] %></p>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <footer class=" bg-dark pt-5 pb-4">
    </footer>
  </body>
</html>

app/views/layouts/homes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>